src/TaobaoExpress.Web/Controllers/RetailerProductsController.cs
namespace TaobaoExpress.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using TaobaoExpress.DataAccess;
    using TaobaoExpress.Services.UoW;

    public class RetailerProductsController : TaobaoExpressBaseController
    {
        private readonly IUnitOfWorkFactory unitOfWorkFactory;

        public RetailerProductsController(IUnitOfWorkFactory unitOfWorkFactory) : base(unitOfWorkFactory)
        {
            this.unitOfWorkFactory = unitOfWorkFactory;
        }

        [HttpGet]
        public ActionResult New(long? id, long amount)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                ViewBag.Amount = amount;
                ViewBag.RetailerId = id.Value;
                ViewBag.Products = unitOfWork.ProductRepository.GetAllProducts();
                return this.PartialView("~/Views/RetailerProducts/EditorTemplates/RetailerProduct.cshtml", new RetailerProduct());
            }
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return this.RedirectToAction("Index", "Retailers");
            }

            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                ViewBag.RetailerId = id.Value;
                ViewBag.Products = unitOfWork.ProductRepository.GetAllProducts();
                var retailerProducts = unitOfWork.RetailerProductRepository.GetRetailerProductsForRetailer(id.Value);
                return this.View(retailerProducts);
            }
        }

        [HttpPost]
        public ActionResult Edit(long id, IEnumerable<RetailerProduct> retailerProducts)
        {
            retailerProducts = retailerProducts ?? new List<RetailerProduct>();

            if (!this.ModelState.IsValid)
            {
                return this.View(retailerProducts);
            }

            return this.ExecuteInUnitOfWork(unitOfWork =>
            {
                var repository = unitOfWork.RetailerProductRepository;

                repository.DeleteItems(id);

                foreach (var retailerProduct in retailerProducts)
                {
                    repository.Add(retailerProduct);
                }
            }, uow => this.RedirectToAction("Index", "Retailers"), badRequestWithUnitOfWork: unitOfWork =>
            {
                ViewBag.RetailerId = id;
                ViewBag.Products = unitOfWork.ProductRepository.GetAllProducts();
                return this.View(retailerProducts);
            });
        }
    }
}

src/TaobaoExpress.Web/Controllers/RetailersController.cs
namespace TaobaoExpress.Controllers
{
    using System.Web.Mvc;
    using TaobaoExpress.DataAccess;
    using TaobaoExpress.Services.UoW;

    public class RetailersController : TaobaoExpressBaseController
    {
        private readonly IUnitOfWorkFactory unitOfWorkFactory;

        public RetailersController(IUnitOfWorkFactory unitOfWorkFactory) : base(unitOfWorkFactory)
        {
            this.unitOfWorkFactory = unitOfWorkFactory;
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var retailer = unitOfWork.RetailerRepository.Get(id);
                if (retailer == null)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                unitOfWork.RetailerRepository.Remove(retailer);
                unitOfWork.Save();
                return this.RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Index(int? page = 0, int? pageSize = 10)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var products = unitOfWork.RetailerRepository.GetRetailersPage(page.Value, pageSize.Value);
                this.ViewBag.Page = page;
                this.ViewBag.PageSize = pageSize;
                return this.View(products);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Retailer retailer)
        {
            return this.Save(retailer, (uow, entity) => this.RedirectToAction(nameof(Index)));
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                var product = new Retailer { Id = -1 };
                return this.View(product);
            }

            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var product = unitOfWork.RetailerRepository.Get(id);
                return this.View(product);
            }
        }
    }
}

src/TaobaoExpress.Web/Views/Retailers/Edit.cshtml
@model TaobaoExpress.DataAccess.Retailer

@{
    var action = this.Model == null ? "Edit" : (this.Model.Id < 0 ? "Create" : "Edit");
    ViewBag.Title = action;
}

<h2>@action</h2>
@this.Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })

@if (this.Model.Id > -1)
{
    <form action="/Retailers/Delete/@Model.Id" method="post">
        <br />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Retailer</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ConcurrencyCheck)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.Updated)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

src/TaobaoExpress.Web/Views/Retailers/Index.cshtml
@using TaobaoExpress.DataAccess
@model IEnumerable<Retailer>
@{
    ViewBag.Title = "Retailers";
}

<h2>Retailers</h2>
@this.Html.ActionLink("Create", "Edit", new { }, new { @class = "btn btn-default" })

<div style="clear: both;">
    @foreach (var retailer in this.Model)
    {
        <div class="card">
            <div class="card-container">
                <h4><b>@retailer.Name</b></h4>
                <p>
                    @this.Html.ActionLink("Edit", "Edit", new { id = retailer.Id }, new { @class = "btn btn-default" })
                    @this.Html.ActionLink("Products", "Edit", "RetailerProducts", new { id = retailer.Id }, new { @class = "btn btn-default" })
                </p>
                <p>Created: @retailer.Created.ToShortDateString() | Updated: @retailer.Updated.ToShortDateString()</p>
            </div>
        </div>
    }
</div>

<div class="footer">
    @if (this.ViewBag.Page > 0)
    {
        @Html.ActionLink("Previous", "Index", new { page = this.ViewBag.Page - 1, pageSize = this.ViewBag.PageSize }, new { @class = "btn btn-default" })
    }
    @if (this.Model.Count() == this.ViewBag.PageSize)
    {
        @Html.ActionLink("Next", "Index", new { page = this.ViewBag.Page + 1, pageSize = this.ViewBag.PageSize }, new { @class = "btn btn-default" })
    }
</div>