src/TaobaoExpress.Web/Controllers/CommentsController.cs
namespace TaobaoExpress.Controllers
{
    using System.Web.Mvc;
    using TaobaoExpress.DataAccess;
    using TaobaoExpress.Services.UoW;

    public class CommentsController : TaobaoExpressBaseController
    {
        public CommentsController(IUnitOfWorkFactory unitOfWorkFactory) : base(unitOfWorkFactory)
        {
        }

        [HttpGet]
        public ActionResult Create(long? id)
        {
            if (id == null)
            {
                return this.RedirectToAction("Index", "Products");
            }

            return this.View(new ProductReview { ProductId = id.Value });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductReview viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            return ExecuteInUnitOfWork(
                unitOfWork => unitOfWork.ProductReviewRepository.AddCommentToPost(viewModel.ProductId, viewModel.UserEmail, viewModel.Text, viewModel.Review),
                unitOfWork => this.RedirectToAction("View", "Products", new { id = viewModel.ProductId }),
                () => this.View());
        }
    }
}

src/TaobaoExpress.Web/Controllers/ProductsController.cs
namespace TaobaoExpress.Controllers
{
    using System;
    using System.Drawing;
    using System.Drawing.Imaging;
    using System.IO;
    using System.Web.Mvc;
    using TaobaoExpress.DataAccess;
    using TaobaoExpress.Services.UoW;

    public class ProductsController : TaobaoExpressBaseController
    {
        private readonly IUnitOfWorkFactory unitOfWorkFactory;

        public ProductsController(IUnitOfWorkFactory unitOfWorkFactory) : base(unitOfWorkFactory)
        {
            this.unitOfWorkFactory = unitOfWorkFactory;
        }

        [HttpGet]
        public ActionResult Index(int? page = 0, int? pageSize = 10)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var products = unitOfWork.ProductRepository.GetProductsPage(page.Value, pageSize.Value);
                this.ViewBag.Page = page;
                this.ViewBag.PageSize = pageSize;
                return this.View(products);
            }
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return this.View(new Product { Id = -1 });
            }

            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var product = unitOfWork.ProductRepository.Get(id);
                return this.View(product);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long? id, Product product)
        {
            this.CopyRequestFileToProductIfAvailable(product);
            return this.Save(product, (uow, entity) => this.RedirectToAction("View", new { id = entity.Id }));
        }

        [HttpGet]
        public ActionResult View(long? id)
        {
            if (id == null)
            {
                return this.Redirect(nameof(Index));
            }

            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var product = unitOfWork.ProductRepository.GetProductWithComments(id.Value);
                this.ViewBag.Related = unitOfWork.RelatedProductRepository.GetRelatedProducts(id.Value);
                return this.View(product);
            }
        }

        [HttpGet]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var product = unitOfWork.ProductRepository.Get(id);
                return this.View(product);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            return this.ExecuteInUnitOfWork(unitOfWork =>
            {
                var related = unitOfWork.RelatedProductRepository.GetRelatedProducts(id);
                foreach (var relatedProduct in related)
                {
                    unitOfWork.RelatedProductRepository.Remove(relatedProduct);
                }

                unitOfWork.Save();
                var product = unitOfWork.ProductRepository.Get(id);
                unitOfWork.ProductRepository.Remove(product);
            }, uow => this.RedirectToAction(nameof(Index)), badRequestWithUnitOfWork: unitOfWork =>
            {
                var product = unitOfWork.ProductRepository.Get(id);
                return this.View(product);
            });
        }

        [HttpGet]
        public ActionResult Image(long id)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var image = unitOfWork.ProductRepository.GetImage(id);
                if (image == null)
                {
                    // return fancy default pic
                    var random = new Random();
                    Color randomColor() => Color.FromArgb(random.Next(0, 255), random.Next(0, 255), random.Next(0, 255), random.Next(0, 255));
                    var bitmap = new Bitmap(500, 500);
                    var graph = Graphics.FromImage(bitmap);
                    graph.Clear(randomColor());
                    graph.FillRectangle(new SolidBrush(randomColor()), new Rectangle(30, 30, 50, 50));
                    graph.FillRectangle(new SolidBrush(randomColor()), new Rectangle(420, 30, 50, 50));
                    graph.FillRectangle(new SolidBrush(randomColor()), new Rectangle(50, 300, 400, 50));
                    using (var memoryStream = new MemoryStream())
                    {
                        bitmap.Save(memoryStream, ImageFormat.Jpeg);
                        return this.File(memoryStream.ToArray(), "image/jpg");
                    }
                }

                return this.File(image, "image/jpg");
            }
        }

        private void CopyRequestFileToProductIfAvailable(Product product)
        {
            if (this.Request.Files.Count > 0)
            {
                for (var i = 0; i < this.Request.Files.Count; i++)
                {
                    var file = this.Request.Files[i];
                    if (file.ContentLength == 0)
                    {
                        if (product.Id > 0)
                        {
                            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
                            {
                                product.Image = unitOfWork.ProductRepository.GetImage(product.Id);
                            }
                        }

                        continue;
                    }

                    if (file.ContentType.StartsWith("image/jpeg") && file.ContentLength > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            file.InputStream.CopyTo(memoryStream);
                            product.Image = memoryStream.ToArray();
                        }
                    }
                    else
                    {
                        this.ModelState.AddModelError("INVALID_FILE", "Please provide a JPG file");
                    }
                }
            }
        }
    }
}

src/TaobaoExpress.Web/Controllers/RelatedProductsController.cs
namespace TaobaoExpress.Controllers
{
    using System.Web.Mvc;
    using TaobaoExpress.DataAccess;
    using TaobaoExpress.Model.Aggregates;
    using TaobaoExpress.Services.UoW;

    public class RelatedProductsController : TaobaoExpressBaseController
    {
        private readonly IUnitOfWorkFactory unitOfWorkFactory;

        public RelatedProductsController(IUnitOfWorkFactory unitOfWorkFactory) : base(unitOfWorkFactory)
        {
            this.unitOfWorkFactory = unitOfWorkFactory;
        }

        [HttpGet]
        public ActionResult Create(long id)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                if (unitOfWork.CreateRepository<DataAccess.Product>().Get(id) == null)
                {
                    return this.RedirectToAction("Index", "Products");
                }

                this.SetPossibleRelatedProducts(id);
                return this.View(new RelatedProduct { ProductId = id });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(long id, RelatedProduct createRelated)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            this.SetPossibleRelatedProducts(createRelated.ProductId);
            return this.ExecuteInUnitOfWork(
                unitOfWork => unitOfWork.RelatedProductRepository.CreateRelatedProduct(createRelated.ProductId, createRelated.RelatedProductId, createRelated.IsSubstitute),
                unitOfWork => this.RedirectToAction("View", "Products", new { id = id }),
                () => this.View(createRelated));
        }

        private void SetPossibleRelatedProducts(long id)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var product = unitOfWork.CreateRepository<DataAccess.Product>().Get(id);
                var possibleRelatedProducts = unitOfWork.ProductRepository.GetPossibleRelatedProducts(id);
                var aggregate = new ProductWithPossibleRelatedProducts(product, possibleRelatedProducts);
                this.ViewBag.Aggregate = aggregate;
            } 
        }
    }
}

src/TaobaoExpress.Web/Views/Products/Delete.cshtml
@model TaobaoExpress.DataAccess.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete @this.Model.Name?</h2>
@this.Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-12">
                Delete Product (last edited: @this.Model.Updated.ToShortDateString()):
                <br />
                @Html.DisplayFor(model => model.Name)
                <br />
                <p>This will delete all product relations</p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Delete" class="btn btn-danger" />
                @Html.ActionLink("Cancel", "View", new { id = this.Model.Id }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

src/TaobaoExpress.Web/Views/Products/Edit.cshtml
@model TaobaoExpress.DataAccess.Product

@{
    var action = this.Model == null ? "Create" : (this.Model.Id < 0 ? "Create" : "Edit");
    ViewBag.Title = action;
}

<h2>@action</h2>
@this.Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })

@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ConcurrencyCheck)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.Updated)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" name="ImagePlaceholder" type="file" />
                @Html.ValidationMessageFor(model => model.Image)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control date-picker" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

src/TaobaoExpress.Web/Views/Products/Index.cshtml
@using TaobaoExpress.DataAccess
@model IEnumerable<Product>
@{
    ViewBag.Title = "Products";
}

<h2>Product List</h2>
@this.Html.ActionLink("Create", "Edit", new { }, new { @class = "btn btn-default" })

<div style="clear: both;">
    @foreach (var product in this.Model)
    {
        <div class="card">
            <img class="card-img" src="/Products/Image/@product.Id" alt="Product Image" style="width: 100%">
            <div class="card-container">
                <h4><b>@product.Name</b></h4>
                <p>
                    @this.Html.ActionLink("View", "View", new { id = product.Id }, new { @class = "btn btn-default" })
                    @this.Html.ActionLink("Edit", "Edit", new { id = product.Id }, new { @class = "btn btn-default" })
                    @this.Html.ActionLink("Delete", "Delete", new { id = product.Id }, new { @class = "btn btn-default" })
                </p>
                <p>Released: @(product.ReleaseDate?.ToShortDateString() ?? "Never") Created: @product.Created.ToShortDateString() | Updated: @product.Updated.ToShortDateString()</p>
            </div>
        </div>
    }
</div>

<div class="footer">
    @if (this.ViewBag.Page > 0)
    {
        @Html.ActionLink("Previous", "Index", new { page = this.ViewBag.Page - 1, pageSize = this.ViewBag.PageSize }, new { @class = "btn btn-default" })
    }
    @if (this.Model.Count() == this.ViewBag.PageSize)
    {
        @Html.ActionLink("Next", "Index", new { page = this.ViewBag.Page + 1, pageSize = this.ViewBag.PageSize }, new { @class = "btn btn-default" })
    }
</div>

src/TaobaoExpress.Web/Views/Products/View.cshtml
@model TaobaoExpress.DataAccess.Product
@using TaobaoExpress.DataAccess

@{
    ViewBag.Title = "View";
}

<h2>@this.Model.Name</h2>
@this.Html.ActionLink("Delete", "Delete", new { id = this.Model.Id }, new { @class = "btn btn-default" })
@this.Html.ActionLink("Edit", "Edit", new { id = this.Model.Id }, new { @class = "btn btn-default" })
@this.Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })

<hr />
<img src="/Products/Image/@this.Model.Id" height="300" />
<br />
@Html.LabelFor(x => x.ReleaseDate)
@Html.DisplayFor(x => x.ReleaseDate)
<br />
@Html.LabelFor(x => x.Updated)
@Html.DisplayFor(x => x.Updated)
<br />
@Html.LabelFor(x => x.Created)
@Html.DisplayFor(x => x.Created)

<h3>Reviews</h3>
@this.Html.ActionLink("Create Comment", "Create", "Comments", new { id = this.Model.Id }, new { @class = "btn btn-default" })

<div class="list-group">
    @foreach (var review in this.Model.ProductReviews)
    {
        <div class="list-group-item">
            <b>@review.UserEmail</b>
            <br />
            <p>@review.Text</p>
            <h6>@review.Review</h6>
            <h6>@review.Created</h6>
        </div>
    }
</div>

<h3>Related Products</h3>
@this.Html.ActionLink("Relate", "Create", "RelatedProducts", new { id = this.Model.Id }, new { @class = "btn btn-default" })

<div class="list-group">
    @foreach (RelatedProduct related in this.ViewBag.Related)
    {
        <div class="list-group-item">
            @{ 
                var id = related.ProductId == this.Model.Id ? related.RelatedProductId : related.ProductId;
            }
            @Html.ActionLink($"Related product with id {id}", "View", "Products", new { id = id }, new { @class = "btn btn-default" })
            @if (related.ProductId == this.Model.Id && related.IsSubstitute)
            {
                <b>Substitute Product</b>
            }
            @if (related.RelatedProductId == this.Model.Id && related.IsSubstitute)
            {
                <b>Parent Substitute Product</b>
            }
        </div>
    }
</div>