src/TaobaoExpress.Web/Controllers/AuditController.cs
namespace TaobaoExpress.Controllers
{
    using System.Web.Mvc;
    using TaobaoExpress.Services.UoW;

    public class AuditController : TaobaoExpressBaseController
    {
        private readonly IUnitOfWorkFactory unitOfWorkFactory;

        public AuditController(IUnitOfWorkFactory unitOfWorkFactory) : base(unitOfWorkFactory)
        {
            this.unitOfWorkFactory = unitOfWorkFactory;
        }

        public ActionResult Index(int? page = 0, int? pageSize = 10)
        {
            using (var unitOfWork = this.unitOfWorkFactory.CreateUnitOfWork())
            {
                var auditLogRepository = unitOfWork.AuditLogRepository;
                var fetched = auditLogRepository.GetAuditLogPage(page.Value, pageSize.Value);
                this.ViewBag.Page = page;
                this.ViewBag.PageSize = pageSize;
                return this.View(fetched);
            }
        }
    }
}

src/TaobaoExpress.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <div class="btn-group" role="group">
            <div class="btn-group" role="group">
                @Html.ActionLink("TaobaoExpress", "Index", "Home", new { }, new { @class = "btn btn-primary" })
            </div>
            <div class="btn-group" role="group">
                @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "btn btn-default" })
            </div>
            <div class="btn-group" role="group">
                @Html.ActionLink("Products", "Index", "Products", new { }, new { @class = "btn btn-default" })
            </div>
            <div class="btn-group" role="group">
                @Html.ActionLink("Retailers", "Index", "Retailers", new { }, new { @class = "btn btn-default" })
            </div>
            <div class="btn-group" role="group">
                @Html.ActionLink("Audit Log", "Index", "Audit", new { }, new { @class = "btn btn-default" })
            </div>
        </div>
        <br />

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 瑞士的淘宝Express</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>